#!/bin/ash

set -e

[ -d /dev/net ] ||
    mkdir -p /dev/net
[ -c /dev/net/tun ] ||
    mknod /dev/net/tun c 10 200

cd /etc/openvpn

[ -f dh.pem ] ||
    openssl dhparam -out dh.pem 1024
[ -f key.pem ] ||
    openssl genrsa -out key.pem 2048 && chmod 600 key.pem
[ -f csr.pem ] ||
    openssl req -new -key key.pem -out csr.pem -subj /CN=OpenVPN/
[ -f cert.pem ] ||
    openssl x509 -req -in csr.pem -out cert.pem -signkey key.pem -days 24855
[ -f server.conf ] ||
    cp server.conf{.dist,}

[ -f client.ovpn ] || cat >client.ovpn <<EOF
client
nobind
dev tun

<key>
`cat key.pem`
</key>
<cert>
`cat cert.pem`
</cert>
<ca>
`cat cert.pem`
</ca>
<dh>
`cat dh.pem`
</dh>

<connection>
remote `wget -q -O - https://api.ipify.org` 1194 udp
</connection>
EOF

iptables -t nat -A POSTROUTING -s 192.168.1.0/24 -o eth0 -j MASQUERADE

echo ""
echo "Client config file available in /etc/openvpn/client.ovpn"
echo "Remember to check the detected IP address"
echo ""

openvpn server.conf
