name: CI

on:
  pull_request:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Detect ffmpeg version
        run: |
          docker build -t maxcanna/ffmpeg:version -f ./ffmpeg/Dockerfile ./ffmpeg
          export FFMPEG_VERSION=$(docker run --rm maxcanna/ffmpeg:version -version | xargs | cut -d ' ' -f 3)
          echo Detected version: $FFMPEG_VERSION
          echo "::set-env name=FFMPEG_VERSION::$FFMPEG_VERSION"
      - name: Build ffmpeg
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6 \
            --output "type=image,push=false" \
            --tag maxcanna/ffmpeg:latest \
            --tag maxcanna/ffmpeg:$FFMPEG_VERSION \
            --file ./ffmpeg/Dockerfile ./ffmpeg
      - name: Detect subliminal version
        run: |
          docker build -t maxcanna/subliminal:version -f ./subliminal/Dockerfile ./subliminal
          export SUBLIMINAL_VERSION=$(docker run --rm maxcanna/subliminal:version --version | cut -d ' ' -f 3)
          echo Detected version: $SUBLIMINAL_VERSION
          echo "::set-env name=SUBLIMINAL_VERSION::$SUBLIMINAL_VERSION"
      - name: Build subliminal
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6 \
            --output "type=image,push=false" \
            --tag maxcanna/subliminal:latest \
            --tag maxcanna/subliminal:$SUBLIMINAL_VERSION \
            --file ./subliminal/Dockerfile ./subliminal
      - name: Detect caddy version
        run: |
          docker build -t maxcanna/caddy:version -f ./caddy/Dockerfile ./caddy
          export CADDY_VERSION=$(docker run --rm maxcanna/caddy:version version | cut -d ' ' -f 1)
          echo Detected version: $CADDY_VERSION
          echo "::set-env name=CADDY_VERSION::$CADDY_VERSION"
      - name: Build caddy
        run: |
          docker buildx build \
            --platform linux/arm/v6 \
            --output "type=image,push=false" \
            --tag maxcanna/caddy:latest \
            --tag maxcanna/caddy:$CADDY_VERSION \
            --file ./caddy/Dockerfile ./caddy
      - name: Build transmission
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6 \
            --output "type=image,push=false" \
            --file ./transmission/Dockerfile ./transmission
      - name: Build minidlna
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6 \
            --output "type=image,push=false" \
            --file ./minidlna/Dockerfile ./minidlna
