FROM alpine
LABEL maintainer="Massimiliano Cannarozzo <massi@massi.dev>"

ARG PUID=1000
ARG PGID=1000
RUN addgroup -S -g ${PGID} app && adduser -S -u ${PUID} -G app app

RUN apk add --no-cache --update ffmpeg

USER app

ENTRYPOINT ["ffmpeg"]
CMD ["-h"]
